extensions_dict = {
    "mp3": "Musics",
    "mp4": "Videos",
    "mkv": "Videos",
    "png": "Images",
    "jpg": "Images",
    "jpeg": "Images",
    "webp": "Images/WEBPs",
    "svg": "Images/SVGs",
    "iso": "ISOs",
    "exe": "Executables",
    "gif": "Gifs",
    "zip": "Archives/ZIPs",
    "rar": "Archives/RARs",
    "7z": "Archives/7z",
    "pdf": "PDFs",
    "doc": "Documents",
    "docx": "Documents",
    "txt": "Texts",
    "xls": "Spreadsheets",
    "xlsx": "Spreadsheets",
    "ppt": "Presentations",
    "pptx": "Presentations",
    "c": "Code/C",
    "cpp": "Code/C++",
    "csa": "Code/C#",
    "py": "Code/Python",
    "js": "Code/Javascript",
    "ts": "Code/Typescript",
    "vue": "Code/Vue",
    "html": "Code/HTML",
    "css": "Code/CSS",
    "sql": "Code/SQL",
    "json": "Code/JSON",
}

def get_target_dir(ext):
    return extensions_dict.get(ext, "Other")